
commands:
  # Hora
  - commmand:
    input:  Que horas são?
    entity: time
    action: getTime
  - commmand:
    input:  Que horas é?
    entity: time
    action: getTime
  - commmand:
    input:  Me digas horas.
    entity: time
    action: getTime
  # Data
  - commmand:
    input:  Qual é a data de hoje?
    entity: time
    action: getDate
  - commmand:
    input:  Data de hoje.
    entity: time
    action: getDate
  - commmand:
    input:  Que dia é hoje?.
    entity: time
    action: getDate
  # Tempo
  - commmand:
    input:  Previsão do tempo
    entity: weather
    action: getWeather
  - commmand:
    input:  Como está o clima?
    entity: weather
    action: getWeather
  # Open
  - commmand:
    input:  Abrir google
    entity: open
    action: 
  - commmand:
    input:  Abra youtube
    entity: open
    action: 
  - commmand:
    input:  Abrir bloco de notas
    entity: open
    action: notepads
  - commmand:
    input:  Abrar o bloco de notas
    entity: open
    action: notepads
    # close
  - commmand:
    input:  Fechar bloco de notas
    entity: close
    action: notepads
  - commmand:
    input:  Parar o bloco de notas
    entity: close
    action: notepads
  - commmand:
    input:  Fechar
    entity: close
    action: 
  - commmand:
    input:  Pare
    entity: close
    action: 